### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by SuperLogan2015** [bettse/Solarbreeze#2]
I was wondering how does this thing work for BLE Portals on IOS or Android?

**Comment by bettse** [comment]
It doesn't work "for" BLE Portals, it works "as" a BLE portal.  It emulates being a portal, like the readme says

**Comment by SuperLogan2015** [comment]
Okay then how do I set the portal emulator up on IOS?

**Comment by SuperLogan2015** [comment]
And to connect the IOS device to android?

**Comment by bettse** [comment]
I'm not sure if it will compile and sideload give how old the code is.  You may need to update the syntax to support the newest version of xcode.

**Comment by NefariousTechSupport** [comment]
I was able to compile and run it, but I can't figure out how this is meant to work, I opened the "Virtual Base" screen and hit the switch, yet there's seemingly nothing happening, there's also the "Second" page, but that seems to be for communicating with the bluetooth portal of power, 
![image](https://github.com/bettse/Solarbreeze/assets/64808609/deae4424-c49a-4f31-9a68-79db749f1448)
some sort of explanation on how to use this once compiled would be greatly appreciated :)

**Comment by bettse** [comment]
@NefariousTechSupport Can you delete your message and open as a new issue?  It seems unrelated to this issue
