### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by NefariousTechSupport** [bettse/Solarbreeze#3]
Hi, I was able to successfully compile the application and install it onto an iOS 12.5.5 iPhone 6+
I booted the application to be greeted to a switch
![image](https://github.com/bettse/Solarbreeze/assets/64808609/a69b8899-86af-496d-af02-899451b62dc1)
Am very unsure as to what to do from here, after hitting the switch i attempted to boot up Skylanders Trap Team iOS and the game didn't recognise it, same with SuperChargers iOS. I then attempted to connect to the iPhone 6+ using another iOS device with the games installed over bluetooth, it was not discoverable.

As a result I'm quite confused as to how to use this project, any explanation as for how to use it after installing would be much appreciated :)

**Comment by bettse** [comment]
Can you check the logs when you run it from xcode?  It's been a while, but from what I recall turning on the switch should enable the advertising of the virtual portal, which Skylanders Trap Team iOS shoudl detect.

Being blank, I think that's because you don't have any tokens.  Looking at the code (https://github.com/bettse/Solarbreeze/blob/master/Solarbreeze/Token.swift#L266-L284) I think you need to load `.bin` files of the skylanders via iTunes file sharing (iirc this is how I did it: https://support.readdle.com/documents/transfer-share-your-files/itunes).  Just to head off a potential question: Don't ask me where to get those.

**Comment by bettse** [comment]
Looking at the code, I think the "second" screen is for connecting to a real portal

**Comment by NefariousTechSupport** [comment]
I uploaded a backup of one of my figures to solarbreeze via iTunes like you suggested and it was being picked up, so thank you for that :)
Trap Team still isn't picking up solarbreeze but I'll examine xcode logs for that shortly as some other work just came up. Thank you for your quick replies, especially on such an old project :)

**Comment by NefariousTechSupport** [comment]
interestingly my ubuntu machine's picking up the device as Skylanders Portal as the code says it should, after experimenting more, i noticed it's not being picked up by other ios devices or windows computers.
Android worked though

**Comment by NefariousTechSupport** [comment]
My other iOS device is an iPhone 7 on iOS 15.8.2

**Comment by NefariousTechSupport** [comment]
xcode logs weren't really reporting anything, selecting a skylander showed S 4 bytes as well as some data about my figure, but since no device with the game on it was detecting my portal, i don't assume it's working, at least not as is.
Thank you so much, if you have any other suggestions then please do let me know, I'll explore making my own since this is very interesting stuff.

**Comment by bettse** [comment]
mind posting the logs?  did they show that it was advertising?  did it give any indication the iOS device running the game was attempting to connect?

**Comment by NefariousTechSupport** [comment]
```
SkylanderToken(7686709d - Spyro xp: 33000/0/0 gold: 9736) selected
S 4 bytes
S 4 bytes
SkylanderToken(7686709d - Spyro xp: 33000/0/0 gold: 9736) selected
S 4 bytes
S 4 bytes
SkylanderToken(7686709d - Spyro xp: 33000/0/0 gold: 9736) selected
S 4 bytes
S 4 bytes
SkylanderToken(7686709d - Spyro xp: 33000/0/0 gold: 9736) selected
S 4 bytes
S 4 bytes

```

**Comment by bettse** [comment]
Ah: maybe try uncommenting some of the prints (ex https://github.com/bettse/Solarbreeze/blob/master/Solarbreeze/BLEPortal.swift#L28 ) that I have commented out

**Comment by NefariousTechSupport** [comment]
Thanks, tried this, no difference in the console logs
Went ahead and uncommented everything and the only difference was a `=> 11 bytes` following `S 4 bytes`
Keep in mind that I'm not using this to communicate with the portal but rather as an emulator

Also tried placing a breakpoint on that function (https://github.com/bettse/Solarbreeze/blob/master/Solarbreeze/BLEPortal.swift#L28) and it was never hit

Messing around with more breakpoints now to try and debug this as well

EDIT: gotta go, won't reply for a while

**Comment by bettse** [comment]
I think I had it backwards and that might be still part of conecting to a real portal.  Add print statements to https://github.com/bettse/Solarbreeze/blob/master/Solarbreeze/FakeBaseInterface.swift and that should show the ble advertisements starting when the switch is flipped.

**Comment by NefariousTechSupport** [comment]
Yep it was showing that it is broadcasting, however when something tries to connect the XPC connection gets invalidated and it resets

I should also state that someone else got it working on two devices running i believe iOS 10

**Comment by bettse** [comment]
> I should also state that someone else got it working on two devices running i believe iOS 10

Good to hear

> connect the XPC connection gets invalidated and it resets

Probably need to google to debug that one.  Could it be permissions or entitlement or something?  the code is from before they made developers add things to info.plist for BLE permission

**Comment by NefariousTechSupport** [comment]
Will do! I'll reply to this thread if I get it working

**Comment by bettse** [comment]
Does #4 basically close this?

**Comment by NefariousTechSupport** [comment]
Yep :)
